"""W6 — EXIF AI 필드 탐지 엔진.

piexif + Pillow XMP 를 이용해 AI 관련 EXIF/XMP 메타데이터를 탐지한다.

판정 흐름:
  FOUND    : AI 키워드가 EXIF 또는 XMP 필드에서 탐지됨
  NOT_FOUND: EXIF 파싱 성공했으나 AI 키워드 없음
  UNKNOWN  : EXIF 파싱 실패 (포맷 미지원 등)
"""
from __future__ import annotations

import io
from typing import Optional

import piexif
from PIL import Image, UnidentifiedImageError

from .base import DetectorBase
from .result import DetectionResult, DetectorOutput

# AI 생성 관련 범용 키워드 (대소문자 무관 비교)
_AI_GENERAL_KEYWORDS: list[str] = [
    "ai generated",
    "ai-generated",
    "aigc",
    "artificial intelligence",
    "generated by ai",
    "ai 생성",
    "ai생성",
]

# Software 필드 AI 도구 키워드
_AI_SOFTWARE_KEYWORDS: list[str] = [
    "stable diffusion",
    "stablediffusion",
    "comfyui",
    "adobe firefly",
    "midjourney",
    "dall-e",
    "dalle",
    "generative ai",
]


class EXIFDetector(DetectorBase):
    """EXIF/XMP AI 관련 필드를 탐지한다.

    확인 필드: UserComment, Software, ImageDescription, MakerNote, XMP
    """

    @property
    def name(self) -> str:
        return "exif"

    def detect(self, image_bytes: bytes) -> DetectorOutput:
        found_in: list[str] = []
        details: dict = {}
        any_check_succeeded = False

        # ── EXIF (piexif) 확인 ──────────────────────────────────────────
        try:
            exif_data = piexif.load(image_bytes)
            any_check_succeeded = True
        except Exception:
            exif_data = None

        if exif_data is not None:
            _check_user_comment(exif_data, found_in, details)
            _check_software(exif_data, found_in, details)
            _check_image_description(exif_data, found_in, details)
            _check_maker_note(exif_data, found_in, details)

        # ── XMP (Pillow) 확인 ────────────────────────────────────────────
        xmp_text = _read_xmp_text(image_bytes)
        if xmp_text is not None:
            any_check_succeeded = True
            if _contains_ai_keyword_any(xmp_text):
                found_in.append("XMP")
                details["xmp_ai_hint"] = xmp_text[:200]

        details["found_in_fields"] = found_in

        if found_in:
            return DetectorOutput(
                result=DetectionResult.FOUND,
                detector_name=self.name,
                details=details,
            )
        if any_check_succeeded:
            return DetectorOutput(
                result=DetectionResult.NOT_FOUND,
                detector_name=self.name,
                details=details,
            )
        return DetectorOutput(
            result=DetectionResult.UNKNOWN,
            detector_name=self.name,
            details={**details, "reason": "exif_not_readable"},
        )


# ---------------------------------------------------------------------------
# 내부 헬퍼 — 각 필드 확인
# ---------------------------------------------------------------------------

def _check_user_comment(
    exif_data: dict, found_in: list[str], details: dict
) -> None:
    raw = exif_data.get("Exif", {}).get(piexif.ExifIFD.UserComment)
    if not raw:
        return
    decoded = decode_user_comment(raw)
    if decoded:
        details["user_comment"] = decoded
        if _contains_ai_keyword_any(decoded):
            found_in.append("UserComment")


def _check_software(
    exif_data: dict, found_in: list[str], details: dict
) -> None:
    raw = exif_data.get("0th", {}).get(piexif.ImageIFD.Software)
    if not raw:
        return
    text = _decode_bytes_latin1(raw)
    if text:
        details["software"] = text
        if _contains_keyword(text.lower(), _AI_GENERAL_KEYWORDS + _AI_SOFTWARE_KEYWORDS):
            found_in.append("Software")


def _check_image_description(
    exif_data: dict, found_in: list[str], details: dict
) -> None:
    raw = exif_data.get("0th", {}).get(piexif.ImageIFD.ImageDescription)
    if not raw:
        return
    text = _decode_bytes_latin1(raw)
    if text:
        details["image_description"] = text
        if _contains_ai_keyword_any(text):
            found_in.append("ImageDescription")


def _check_maker_note(
    exif_data: dict, found_in: list[str], details: dict
) -> None:
    raw = exif_data.get("Exif", {}).get(piexif.ExifIFD.MakerNote)
    if not raw:
        return
    try:
        text = raw.decode("latin-1")
        if _contains_ai_keyword_any(text):
            found_in.append("MakerNote")
    except Exception:
        pass


def _read_xmp_text(image_bytes: bytes) -> Optional[str]:
    """Pillow 로 XMP 텍스트를 읽는다. 없으면 None."""
    try:
        img = Image.open(io.BytesIO(image_bytes))
        # JPEG: APP1 세그먼트 XMP
        xmp = img.info.get("XML:com.adobe.xmp") or img.info.get("xmp")
        if xmp:
            return xmp if isinstance(xmp, str) else xmp.decode("utf-8", errors="replace")
        return None
    except (UnidentifiedImageError, Exception):
        return None


# ---------------------------------------------------------------------------
# 공개 헬퍼 — 테스트에서도 사용
# ---------------------------------------------------------------------------

def decode_user_comment(raw: bytes) -> Optional[str]:
    """EXIF UserComment raw bytes 에서 텍스트를 추출한다.

    ISO 8859-1(EXIF 2.3) 문자 코드 프리픽스를 처리한다.
    """
    if not raw:
        return None
    prefixes: list[tuple[bytes, str]] = [
        (b"ASCII\x00\x00\x00", "ascii"),
        (b"UNICODE\x00", "utf-16-le"),
        (b"JIS\x00\x00\x00\x00\x00", "iso-2022-jp"),
    ]
    for prefix, enc in prefixes:
        if raw.startswith(prefix):
            payload = raw[len(prefix):]
            try:
                return payload.decode(enc).rstrip("\x00").strip()
            except (UnicodeDecodeError, LookupError):
                return None
    # 프리픽스 없음 — latin-1 폴백
    try:
        return raw.decode("latin-1").strip()
    except Exception:
        return None


def _decode_bytes_latin1(raw: bytes) -> Optional[str]:
    try:
        return raw.decode("latin-1").rstrip("\x00").strip()
    except Exception:
        return None


def _contains_ai_keyword_any(text: str) -> bool:
    return _contains_keyword(text.lower(), _AI_GENERAL_KEYWORDS + _AI_SOFTWARE_KEYWORDS)


def _contains_keyword(text_lower: str, keywords: list[str]) -> bool:
    return any(kw in text_lower for kw in keywords)
