"""W2 Task2 — EXIF AI 관련 표준 필드 목록 확정 및 읽기 테스트.

조사 결과:
  - 범용 AI 표시 EXIF 표준은 아직 없음 (2026년 기준)
  - 도구별 관행 필드를 정리하고 읽기 가능성을 검증
  - piexif(IFD 기반) + Pillow(XMP/raw) 조합으로 커버

표준 후보 필드:
  IFD 0th  : ImageDescription, Software
  EXIF IFD : UserComment, MakerNote
  XMP      : dc:description, xmpRights:UsageTerms,
             Iptc4xmpCore:Subject, 도구별 네임스페이스
"""
import io

import piexif
from PIL import Image

# ---------------------------------------------------------------------------
# 조사된 AI 관련 EXIF 필드 카탈로그
# ---------------------------------------------------------------------------

# 범용 EXIF IFD 필드 (piexif 태그 번호)
AI_EXIF_FIELDS = {
    "UserComment": piexif.ExifIFD.UserComment,       # 0x9286 — 가장 흔히 사용
    "MakerNote": piexif.ExifIFD.MakerNote,           # 0x927C — 도구 고유 메타
}

# 범용 0th IFD 필드
AI_0TH_FIELDS = {
    "ImageDescription": piexif.ImageIFD.ImageDescription,  # 0x010E
    "Software": piexif.ImageIFD.Software,                  # 0x0131
    "Artist": piexif.ImageIFD.Artist,                      # 0x013B
    "Copyright": piexif.ImageIFD.Copyright,                # 0x8298
}

# 도구별 XMP 네임스페이스 (읽기: Pillow getxmp() / info["XML:com.adobe.xmp"])
AI_XMP_NAMESPACES = {
    "stable_diffusion": "http://ns.adobe.com/xap/1.0/",   # parameters 필드
    "dc": "http://purl.org/dc/elements/1.1/",             # dc:description
    "xmp_rights": "http://ns.adobe.com/xap/1.0/rights/",  # UsageTerms
    "iptc4_xmpcore": "http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/",
}

# UserComment 충족 키워드 (탐지 패턴 초안)
USER_COMMENT_AI_KEYWORDS = [
    "AI Generated",
    "AI-Generated",
    "AIGC",
    "artificial intelligence",
    "Artificial Intelligence",
    "generated by ai",
    "AI 생성",
]


# ---------------------------------------------------------------------------
# Helper: JPEG with EXIF
# ---------------------------------------------------------------------------

def _make_jpeg_with_exif(exif_dict: dict) -> bytes:
    img = Image.new("RGB", (32, 32), color=(128, 128, 128))
    buf = io.BytesIO()
    img.save(buf, format="JPEG", exif=piexif.dump(exif_dict))
    return buf.getvalue()


def _read_exif(jpeg_bytes: bytes) -> dict:
    return piexif.load(jpeg_bytes)


# ---------------------------------------------------------------------------
# 테스트: piexif 읽기 가능성
# ---------------------------------------------------------------------------

class TestPiexifFieldReadability:
    """piexif 로 AI 관련 EXIF 필드를 읽을 수 있음을 검증한다."""

    def test_user_comment_round_trip(self):
        """UserComment 필드 쓰기·읽기 왕복이 성공해야 한다."""
        payload = b"ASCII\x00\x00\x00AI Generated"
        exif = {
            "0th": {},
            "Exif": {piexif.ExifIFD.UserComment: payload},
            "GPS": {},
            "1st": {},
        }
        data = _make_jpeg_with_exif(exif)
        loaded = _read_exif(data)
        assert loaded["Exif"][piexif.ExifIFD.UserComment] == payload

    def test_image_description_round_trip(self):
        """ImageDescription 필드 쓰기·읽기가 성공해야 한다."""
        desc = b"AI Generated Image"
        exif = {
            "0th": {piexif.ImageIFD.ImageDescription: desc},
            "Exif": {},
            "GPS": {},
            "1st": {},
        }
        data = _make_jpeg_with_exif(exif)
        loaded = _read_exif(data)
        assert loaded["0th"][piexif.ImageIFD.ImageDescription] == desc

    def test_software_field_round_trip(self):
        """Software 필드 (생성 도구 명) 읽기가 성공해야 한다."""
        software = b"StableDiffusion 2.1"
        exif = {
            "0th": {piexif.ImageIFD.Software: software},
            "Exif": {},
            "GPS": {},
            "1st": {},
        }
        data = _make_jpeg_with_exif(exif)
        loaded = _read_exif(data)
        assert loaded["0th"][piexif.ImageIFD.Software] == software

    def test_maker_note_round_trip(self):
        """MakerNote 필드 (도구 고유 바이너리) 쓰기·읽기가 성공해야 한다."""
        maker_note = b"\x00\x01\x02TOOL_SPECIFIC_AI_FLAG"
        exif = {
            "0th": {},
            "Exif": {piexif.ExifIFD.MakerNote: maker_note},
            "GPS": {},
            "1st": {},
        }
        data = _make_jpeg_with_exif(exif)
        loaded = _read_exif(data)
        assert loaded["Exif"][piexif.ExifIFD.MakerNote] == maker_note

    def test_missing_ai_field_returns_none(self):
        """AI 필드가 없을 때 KeyError 없이 None 처리가 가능해야 한다."""
        exif = {"0th": {}, "Exif": {}, "GPS": {}, "1st": {}}
        data = _make_jpeg_with_exif(exif)
        loaded = _read_exif(data)
        user_comment = loaded["Exif"].get(piexif.ExifIFD.UserComment)
        assert user_comment is None


class TestUserCommentDecoding:
    """UserComment 바이트 디코딩 로직 검증."""

    def _decode_user_comment(self, raw: bytes) -> str | None:
        """ASCII/Unicode prefix 를 제거하고 사람이 읽는 문자열을 반환한다."""
        if not raw:
            return None
        prefixes = {
            b"ASCII\x00\x00\x00": "ascii",
            b"UNICODE\x00": "utf-16-le",
            b"JIS\x00\x00\x00\x00\x00": "iso-2022-jp",
        }
        for prefix, enc in prefixes.items():
            if raw.startswith(prefix):
                payload = raw[len(prefix):]
                try:
                    return payload.decode(enc).rstrip("\x00").strip()
                except UnicodeDecodeError:
                    return None
        # prefix 없음 — 그대로 latin-1 시도
        try:
            return raw.decode("latin-1").strip()
        except Exception:
            return None

    def test_ascii_prefix_decoded(self):
        raw = b"ASCII\x00\x00\x00AI Generated"
        result = self._decode_user_comment(raw)
        assert result == "AI Generated"

    def test_unicode_prefix_decoded(self):
        text = "AI 생성"
        raw = b"UNICODE\x00" + text.encode("utf-16-le")
        result = self._decode_user_comment(raw)
        assert result == text

    def test_empty_returns_none(self):
        assert self._decode_user_comment(b"") is None

    def test_no_prefix_fallback(self):
        raw = b"AI Generated"
        result = self._decode_user_comment(raw)
        assert result is not None
        assert "AI" in result


class TestAiKeywordDetection:
    """UserComment 에서 AI 키워드 탐지 로직 검증."""

    def _contains_ai_keyword(self, text: str) -> bool:
        lower = text.lower()
        keywords = [k.lower() for k in USER_COMMENT_AI_KEYWORDS]
        return any(k in lower for k in keywords)

    def test_en_ai_generated_detected(self):
        assert self._contains_ai_keyword("AI Generated")

    def test_en_aigc_detected(self):
        assert self._contains_ai_keyword("AIGC content")

    def test_ko_ai_generated_detected(self):
        assert self._contains_ai_keyword("이 이미지는 AI 생성 콘텐츠입니다")

    def test_no_ai_keyword_returns_false(self):
        assert not self._contains_ai_keyword("Photo taken at Seoul")

    def test_case_insensitive(self):
        assert self._contains_ai_keyword("ai generated")
        assert self._contains_ai_keyword("AI GENERATED")


class TestKnownToolExifPatterns:
    """실제 AI 도구별 EXIF 패턴 문서화 및 검증."""

    TOOL_PATTERNS = {
        "stable_diffusion": {
            "field": "Software",
            "example": b"Stable Diffusion",
            "note": "Software 필드에 모델명 기재. XMP parameters 에 프롬프트 포함.",
        },
        "comfyui": {
            "field": "UserComment",
            "example": b"ASCII\x00\x00\x00ComfyUI",
            "note": "workflow JSON을 UserComment 에 임베드하는 경우 있음.",
        },
        "adobe_firefly": {
            "field": "C2PA",
            "example": None,  # C2PA 매니페스트로 표시, EXIF 아님
            "note": "C2PA 매니페스트 방식. EXIF 필드 미사용.",
        },
        "midjourney": {
            "field": None,
            "example": None,  # EXIF AI 필드 미삽입
            "note": "EXIF AI 필드 없음. 워터마크도 없음. 탐지 불가 → UNKNOWN.",
        },
        "dall_e": {
            "field": None,
            "example": None,
            "note": "EXIF AI 필드 없음. C2PA 미지원(2026 기준). → UNKNOWN.",
        },
    }

    def test_tool_patterns_documented(self):
        assert len(self.TOOL_PATTERNS) >= 5

    def test_stable_diffusion_software_field(self):
        pattern = self.TOOL_PATTERNS["stable_diffusion"]
        exif = {
            "0th": {piexif.ImageIFD.Software: pattern["example"]},
            "Exif": {},
            "GPS": {},
            "1st": {},
        }
        data = _make_jpeg_with_exif(exif)
        loaded = _read_exif(data)
        software = loaded["0th"].get(piexif.ImageIFD.Software, b"")
        assert b"Stable Diffusion" in software

    def test_midjourney_unknown_classification(self):
        """Midjourney 이미지는 AI 필드가 없어 UNKNOWN 으로 분류돼야 함."""
        pattern = self.TOOL_PATTERNS["midjourney"]
        assert pattern["field"] is None
        assert pattern["example"] is None
        # 탐지 불가 → 탐지 엔진 반환값은 UNKNOWN

    def test_dall_e_unknown_classification(self):
        """DALL-E 이미지도 EXIF AI 필드 없음 → UNKNOWN."""
        pattern = self.TOOL_PATTERNS["dall_e"]
        assert pattern["field"] is None

    def test_xmp_namespace_catalog_complete(self):
        """XMP 네임스페이스 카탈로그가 최소 3개 이상 정의되어야 한다."""
        assert len(AI_XMP_NAMESPACES) >= 3

    def test_ai_exif_field_catalog_complete(self):
        """AI 관련 필드 카탈로그가 최소 2개 이상 정의되어야 한다."""
        assert len(AI_EXIF_FIELDS) >= 2
        assert len(AI_0TH_FIELDS) >= 3
